<?php

return [
    'reason_manual_ban' => 'Added manually by administrator',
    'reason_is_search_engine' => 'Search engine bot',
    'reason_is_google' => 'Google bot',
    'reason_is_bing' => 'Bing bot',
    'reason_is_yahoo' => 'Yahoo bot',
    'reason_too_many_sessions' => 'Too many sessions',
    'reason_too_many_accesses' => 'Too many accesses',
    'reason_empty_js_cookie' => 'Cannot create JS cookies',
    'reason_empty_referer' => 'Empty referrer',
    'reason_reached_limit_day' => 'Daily limit reached',
    'reason_reached_limit_hour' => 'Hourly limit reached',
    'reason_reached_limit_minute' => 'Minutely limit reached',
    'reason_reached_limit_second' => 'Secondly limit reached',

    // Message
    'error_mysql_connection' => 'Cannot access to your MySQL database, please check your settings.',
    'error_mysql_driver_not_supported' => 'Your system doesn’t support MySQL driver.',
    'error_sqlite_driver_not_supported' => 'Your system doesn’t support SQLite driver.',
    'error_sqlite_directory_not_writable' => 'SQLite data driver requires the storage directory writable.',
    'error_redis_driver_not_supported' => 'Your system doesn’t support Redis driver.',
    'error_file_directory_not_writable' => 'File data driver requires the storage directory writable.',
    'error_logger_directory_not_writable' => 'Action Logger requires the storage directory writable.',
    'success_settings_saved' => 'Settings saved',

    // Others.
    'field_not_visible' => 'Cannot view this field in demo mode.',
    'permission_required' => 'Permission required.',

    // Header status bar.
    'channel' => 'Channel',
    'mode' => 'Mode',
    'logout' => 'Logout',

    // Setting - authentication page.
    'auth_heading' => 'Authentication',
    'auth_description' => 'The HTTP WWW-Authenticate response header defines the authentication method that should be used to gain access to a resource.',
    'auth_label_url_path' => 'URL Path',
    'auth_label_username' => 'Username',
    'auth_label_password' => 'Password',
    'auth_btn_submit' => 'Submit',
    'auth_label_encrypted' => 'encrypted',
    'auth_label_remove' => 'Remove',

    // Setting - exclusion page.
    'excl_heading' => 'Exclusion',
    'excl_description' => 'Please enter the begin with URLs you want them excluded from Shieldon protection.',

    // IP Manager
    'ipma_heading' => 'IP Manager',
    'ipma_description' => 'IP Manager is not like Rule Table (effective period depends on the data cycle), everything you have done here is permanent.',
    'ipma_label_ip' => 'IP',
    'ipma_label_order' => 'Order',
    'ipma_label_rule' => 'Rule',
    'ipma_label_action' => 'Action',
    'ipma_label_plz_select' => 'Please select',
    'ipma_label_remove_ip' => 'Remove this IP',
    'ipma_label_allow_ip' => 'Allow this IP',
    'ipma_label_deny_ip' => 'Deny this IP',

    // Log
    'log_heading_captchas' => 'CAPTCHAs',
    'log_note_captcha_last_month' => 'CAPTCHA statistic last month',
    'log_heading_pageviews' => 'Pageviews',
    'log_note_pageview_last_month' => 'Total pageviews last month',

    'log_label_last_month' => 'Last month',
    'log_label_this_month' => 'This month',
    'log_label_last_7_days' => 'Last 7 days',
    'log_label_yesterday' => 'Yesterday',
    'log_label_today' => 'Today',
    'log_msg_no_logger' => 'Sorry, you have to implement ActionLogger to use this function.',
    'log_label_in_queue' => 'In queue',
    'log_label_in_blacklist' => 'In blacklist',
    'log_label_captcha' => 'CAPTCHA',
    'log_label_pageviews' => 'Pageviews',
    'log_label_session' => 'Sessions',
    'log_label_solved' => 'solved',
    'log_label_failed' => 'failed',
    'log_label_displays' => 'displays',
    'log_label_timezone' => 'Timezone',
    'log_note_captcha_last_7_days',

    // Overview
    'overview_heading_data_circle' => 'Data Circle',
    'overview_label_mysql' => 'MySQL',
    'overview_text_rows' => 'rows',
    'overview_note_sql_db' => 'SQL database.',
    'overview_note_memory_db' =>  'In-memory dadabase.',
    'overview_label_redis' => 'Redis',
    'overview_btn_document' => 'Document',
    'overview_btn_close' => 'Close',
    'overview_btn_save' => 'SAVE',
    'overview_note_image_captcha' => 'A simple text-in-image Captcha.',
    'overview_label_image_captcha' => 'Image Captcha',
    'overview_note_recaptcha' => 'Provided by Google.',
    'overview_label_recaptcha' => 'reCAPTCHA',
    'overview_heading_captcha' => 'Captcha Modules',
    'overview_note_action_logger' => 'Record every visitor’s behavior.',
    'overview_label_action_logger' => 'Action Logger',
    'overview_heading_logger' => 'Logger',
    'overview_text_since' => 'since',
    'overview_text_days' => 'days',
    'overview_text_size' => 'size',
    'overview_note_useragent' => 'Analysis user-agent information from visitors.',
    'overview_label_useragent' => 'User Agent',
    'overview_note_rdns' => 'Identify IP resolved hostname (RDNS) from visitors.',
    'overview_label_rdns' => 'RDNS',
    'overview_note_header' => 'Analyze header information from visitors.',
    'overview_label_header' => 'Header',
    'overview_note_trustedbot' => 'Allow popular search engines crawl your website.',
    'overview_label_trustedbot' => 'Trusted Bot',
    'overview_note_ip' => 'Advanced IP address mangement.',
    'overview_label_ip' => 'IP',
    'overview_heading_components' => 'Components',
    'overview_note_referer' => 'Check HTTP referrer information.',
    'overview_label_referer' => 'Referrer',
    'overview_note_frequency' => 'Check how often does a visitor view the pages.',
    'overview_label_frequency' => 'Frequency',
    'overview_note_session' => 'Detect multiple sessions created by the same visitor.',
    'overview_label_session' => 'Session',
    'overview_note_cookie' => 'Check if visitors can create cookie by JavaScript.',
    'overview_label_cookie' => 'Cookie',
    'overview_heading_filters' => 'Filters',
    'overview_label_sqlite' => 'SQLite',
    'overview_note_file_system' => 'File system.',
    'overview_label_file' => 'File',
    'overview_text_more_usages' => 'For more usages please check out that document.',

    // IP log table.
    'table_heading_ip_log' => 'IP Log Table',
    'table_description_ip_log_1' => 'This is where the Shieldon records the users’ strange behavior.',
    'table_description_ip_log_2' => 'All processes are automatic and instant, you can ignore that.',
    'table_description_ip_log_3' => 'IP log table will be all cleared after new cycle begins.',
    'table_label_resolved_hostname' => 'Resolved hostname',
    'table_label_last_visit' => 'Last visit',
    'table_label_flags' => 'Flags',

    // Rule table.
    'table_heading_rule' => 'Rule Table',
    'table_description_rule_1' => 'This is where the Shieldon temporarily allows or denys users in current cycle.',
    'table_description_rule_2' => 'All processes are automatic and instant, you can ignore that.',
    'table_description_rule_3' => 'Rule table will be reset after new cycle begins.',
    'table_label_deny_ip_temporarily' => 'Deny this IP temporarily',
    'table_label_deny_ip_permanently' => 'Deny this IP permanently',
    'table_ip_placeholder' => 'Please fill in an IP address..',
    'table_label_type' => 'Type',
    'table_label_reason' => 'Reason',
    'table_label_time' => 'Time',
    'table_label_remove' => 'Remove',

    // Session table.
    'table_heading_session' => 'Session Table',
    'table_label_remain_seconds' => 'Remain Seconds',
    'table_label_priority' => 'Priority',
    'table_label_status' => 'Status',
    'table_label_session_id' => 'Session ID',
    'table_text_allowable' => 'Allowable',
    'table_text_expired' => 'Expired',
    'table_text_waiting' => 'Waiting',
    'table_description_session_1' => 'Read-time logs for <strong>Online Session Controll</strong>. All processes are automatic and instant, you can ignore that.',
    'table_description_session_2' => 'Notice this is only working when you have enabled that function.',
    'table_heading_limit' => 'Limit',
    'table_note_limit' => 'Online session limit.',
    'table_heading_period' => 'Period',
    'table_note_period' => 'Keep-alive period. (minutes)',
    'table_heading_online' => 'Online',
    'table_note_online' => 'Online session limit.',

    // Xss protection.
    'xss_heading' => 'XSS Protection',
    'xss_description' => 'Prevent Cross site scripting (XSS) attacks.',
    'xss_label_variable' => 'Variable',
    'xss_text_eradicate_injection' => 'Eradicate potential injection string for single variable.',
    'xss_label_single_variable' => 'Single variable',
    'xss_label_variable_name' => 'Variable Name',
    'xss_text_update_above_settings' => 'Update above settings.',
    'xss_text_filter_cookie_variables' => 'Filter all COOKIE method variables.',
    'xss_text_filter_get_variables' => 'Filter all GET method variables.',
    'xss_text_filter_post_variables' => 'Filter all POST method variables.',
];
