<?php
// phpcs:disable Generic.Files.LineLength

return [
    'deny_title' => '禁止连线',
    'deny_heading' => '禁止连！',
    'deny_message' => '您的IP位址已被封锁。',
    'limit_title' => '请排队',
    'limit_heading' => '请排队',
    'limit_message' => '这个网站正限制在线浏览人数。请稍候。',
    'stop_title' => '请解决 CAPTCHA 验证',
    'stop_heading' => '偵測到不尋常的行為',
    'stop_message' => '请完成 CAPTCHA 验证确认您是人类。',
    'stop_submit' => '送出',
    'credit' => '这个网站由 {0} 开源专案防护。',
    'lineup_info' => '排在您之前的人数：{0}',
    'online_info' => '在线人数：{0}',
    'keepalive_info' => '在进入后,每位使用者有 {0} 秒钟的时间可以检视这个页面。',

    // @since 0.1.7
    'messenger_text_ip' => 'IP',
    'messenger_text_rdns' => 'RDNS',
    'messenger_text_time' => '时间',
    'messenger_text_timezone' => '时区',
    'messenger_text_cpu' => 'CPU使用量',
    'messenger_text_memory' => '记忆体使用量',
    'messenger_text_reason' => '理由',
    'messenger_text_system' => '系统状态',
    'messenger_text_reason_code_1' => '太多工作阶段。',
    'messenger_text_reason_code_2' => '太多连线。',
    'messenger_text_reason_code_3' => '无法建立JS Cookie。',
    'messenger_text_reason_code_4' => '空的来源网址。',
    'messenger_text_reason_code_11' => '达到每日限制。',
    'messenger_text_reason_code_12' => '达到每小时限制。',
    'messenger_text_reason_code_13' => '达到每分限制。',
    'messenger_text_reason_code_14' => '达到每秒限制。',
    'messenger_text_handle' => '处置',
    'messenger_text_handle_type_1' => '这个IP已经在当前的资料周期被永久封锁,直到重设资料周期为止。',
    'messenger_text_handle_type_2' => '这个IP已经被放到iptables防火墙的DROP列表,直到伺服器重开机为止。',
];
