<?php

return [
    'deny_title' => 'Access Denied',
    'deny_heading' => 'Access Denied',
    'deny_message' => 'The IP address you are using has been blocked.',
    'limit_title' => 'Please Queue',
    'limit_heading' => 'Please Queue',
    'limit_message' => 'This page is limiting the number of online users. Please wait for a moment.',
    'stop_title' => 'Please Complete the CAPTCHA',
    'stop_heading' => 'Unusual Behavior Detected',
    'stop_message' => 'Please complete the CAPTCHA to confirm you are human.',
    'stop_submit' => 'Submit',
    'credit' => 'This website is protected by the {0} open source project.',
    'lineup_info' => 'Number of users ahead of you: {0}',
    'online_info' => 'Online users: {0}',
    'keepalive_info' => 'Upon entry, each user has {0} seconds to view this page.',
    'messenger_notification_subject' => 'Notification for IP: {0}!',

    // @since 0.1.7
    'messenger_text_ip' => 'IP',
    'messenger_text_rdns' => 'RDNS',
    'messenger_text_time' => 'Time',
    'messenger_text_timezone' => 'Timezone',
    'messenger_text_cpu' => 'CPU Usage',
    'messenger_text_memory' => 'Memory Usage',
    'messenger_text_reason' => 'Reason',
    'messenger_text_system' => 'System Status',
    'messenger_text_reason_code_1' => 'Too many sessions.',
    'messenger_text_reason_code_2' => 'Too many accesses.',
    'messenger_text_reason_code_3' => 'Cannot create JS cookies.',
    'messenger_text_reason_code_4' => 'Empty referrer.',
    'messenger_text_reason_code_11' => 'Daily limit reached.',
    'messenger_text_reason_code_12' => 'Hourly limit reached.',
    'messenger_text_reason_code_13' => 'Minute limit reached.',
    'messenger_text_reason_code_14' => 'Second limit reached.',
    'messenger_text_handle' => 'Handle',
    'messenger_text_handle_type_1' => 'This IP has been permanently banned for the current data cycle until data is reset.', // phpcs:ignore
    'messenger_text_handle_type_2' => 'This IP has been added to iptables’ DROP list until the server is rebooted.',
    'messenger_text_mail_subject' => 'Notification from Shieldon Firewall.',
];
